import { describe, expect, it } from "vitest";
import {
  isCssDeliveryAnalyzerResponse,
  isFontLoadingAnalyzerResponse,
  isJavaScriptBundleSurfaceResponse,
} from "./asset-delivery-tool-contract";

const base = {
  generated_at: "2026-07-22T00:00:00Z",
  requested_url: "https://example.com/",
  final_url: "https://example.com/",
  status_code: 200,
  content_type: "text/html",
  redirect_count: 0,
  truncated: false,
  status: "warning" as const,
  recommendation: "Review the result.",
};

const finding = {
  id: "sample-finding",
  title: "Sample finding",
  severity: "medium" as const,
  value: "1",
  recommendation: "Review it.",
};

describe("asset delivery tool contracts", () => {
  it("accepts a valid JavaScript bundle surface response", () => {
    expect(isJavaScriptBundleSurfaceResponse({
      ...base,
      contract_version: "webdiag.tool.javascript_bundle_surface.v1",
      scan_mode: "static_html_bounded_headers",
      discovered_script_count: 1,
      unique_script_count: 1,
      checked_script_count: 1,
      same_host_script_count: 1,
      cross_host_script_count: 0,
      module_script_count: 0,
      classic_script_count: 1,
      parser_blocking_candidate_count: 1,
      duplicate_src_count: 0,
      known_declared_bytes: 1000,
      unknown_size_count: 0,
      compressed_response_count: 1,
      long_cache_count: 1,
      failed_asset_count: 0,
      issue_count: 1,
      assets: [{
        position: 1,
        raw_src: "/app.js",
        resolved_url: "https://example.com/app.js",
        final_url: "https://example.com/app.js",
        hostname: "example.com",
        same_host: true,
        script_kind: "classic",
        async_attribute: false,
        defer_attribute: false,
        parser_blocking_candidate: true,
        fetch_state: "ok",
        status_code: 200,
        content_type: "application/javascript",
        declared_bytes: 1000,
        content_encoding: "gzip",
        cache_control: "public, max-age=31536000, immutable",
        max_age_seconds: 31536000,
        immutable_cache: true,
        redirect_count: 0,
        issues: [],
      }],
      findings: [finding],
    })).toBe(true);
  });

  it("accepts valid CSS and font-loading responses", () => {
    expect(isCssDeliveryAnalyzerResponse({
      ...base,
      contract_version: "webdiag.tool.css_delivery_analyzer.v1",
      scan_mode: "static_html_bounded_css",
      stylesheet_link_count: 1,
      unique_stylesheet_count: 1,
      checked_stylesheet_count: 1,
      inline_style_block_count: 0,
      inline_style_bytes: 0,
      same_host_stylesheet_count: 1,
      cross_host_stylesheet_count: 0,
      default_media_candidate_count: 1,
      conditional_media_count: 0,
      alternate_or_disabled_count: 0,
      duplicate_href_count: 0,
      known_declared_bytes: 1000,
      sampled_decoded_bytes: 2000,
      compressed_response_count: 1,
      import_rule_count: 0,
      font_face_rule_count: 1,
      failed_stylesheet_count: 0,
      issue_count: 0,
      stylesheets: [{
        position: 1,
        raw_href: "/app.css",
        resolved_url: "https://example.com/app.css",
        final_url: "https://example.com/app.css",
        hostname: "example.com",
        same_host: true,
        media: null,
        default_media_candidate: true,
        alternate: false,
        disabled: false,
        fetch_state: "ok",
        status_code: 200,
        content_type: "text/css",
        declared_bytes: 1000,
        sampled_decoded_bytes: 2000,
        content_encoding: "gzip",
        cache_control: "public, max-age=31536000",
        max_age_seconds: 31536000,
        immutable_cache: false,
        import_rule_count: 0,
        font_face_rule_count: 1,
        source_map_comment: false,
        redirect_count: 0,
        issues: [],
      }],
      findings: [],
    })).toBe(true);

    expect(isFontLoadingAnalyzerResponse({
      ...base,
      contract_version: "webdiag.tool.font_loading_analyzer.v1",
      scan_mode: "static_html_bounded_css",
      stylesheet_count: 1,
      checked_stylesheet_count: 1,
      font_face_count: 1,
      family_count: 1,
      font_source_count: 1,
      unique_font_source_count: 1,
      checked_font_source_count: 1,
      local_source_count: 0,
      preload_count: 1,
      matched_preload_count: 1,
      missing_font_display_count: 0,
      blocking_font_display_count: 0,
      swap_or_optional_count: 1,
      cross_host_font_count: 0,
      woff2_source_count: 1,
      duplicate_source_count: 0,
      known_declared_bytes: 20000,
      unknown_size_count: 0,
      failed_font_count: 0,
      issue_count: 0,
      faces: [{
        position: 1,
        family: "Main",
        style: "normal",
        weight: "400",
        display: "swap",
        source_stylesheet_url: "https://example.com/app.css",
        fetchable_source_count: 1,
        local_source_count: 0,
        issues: [],
      }],
      assets: [{
        position: 1,
        resolved_url: "https://example.com/main.woff2",
        final_url: "https://example.com/main.woff2",
        hostname: "example.com",
        same_host: true,
        families: ["Main"],
        format_hints: ["woff2"],
        preloaded: true,
        fetch_state: "ok",
        status_code: 200,
        content_type: "font/woff2",
        declared_bytes: 20000,
        content_encoding: null,
        cache_control: "public, max-age=31536000, immutable",
        max_age_seconds: 31536000,
        immutable_cache: true,
        redirect_count: 0,
        issues: [],
      }],
      preloads: [{
        position: 1,
        raw_href: "/main.woff2",
        resolved_url: "https://example.com/main.woff2",
        type_value: "font/woff2",
        crossorigin_present: true,
        matches_discovered_font: true,
        issues: [],
      }],
      findings: [],
    })).toBe(true);
  });

  it("rejects wrong versions, negative counts, and malformed nested fields", () => {
    expect(isJavaScriptBundleSurfaceResponse({ ...base, contract_version: "wrong" })).toBe(false);
    expect(isCssDeliveryAnalyzerResponse({
      ...base,
      contract_version: "webdiag.tool.css_delivery_analyzer.v1",
      scan_mode: "static_html_bounded_css",
      stylesheet_link_count: -1,
      stylesheets: [],
      findings: [],
    })).toBe(false);
    expect(isFontLoadingAnalyzerResponse({
      ...base,
      contract_version: "webdiag.tool.font_loading_analyzer.v1",
      scan_mode: "static_html_bounded_css",
      stylesheet_count: 0,
      checked_stylesheet_count: 0,
      font_face_count: 0,
      family_count: 0,
      font_source_count: 0,
      unique_font_source_count: 0,
      checked_font_source_count: 0,
      local_source_count: 0,
      preload_count: 0,
      matched_preload_count: 0,
      missing_font_display_count: 0,
      blocking_font_display_count: 0,
      swap_or_optional_count: 0,
      cross_host_font_count: 0,
      woff2_source_count: 0,
      duplicate_source_count: 0,
      known_declared_bytes: 0,
      unknown_size_count: 0,
      failed_font_count: 0,
      issue_count: 0,
      faces: [{ issues: "not-an-array" }],
      assets: [],
      preloads: [],
      findings: [],
    })).toBe(false);
  });
});
