"use client";
import { useState, type FormEvent } from "react";
import type { Locale } from "@webdiag/tool-registry";
import { isHeadingStructureResponse, isKeywordFrequencyResponse, isReadabilityResponse, isToolErrorPayload, parseContentToolUrlInput, type ContentAnalysisToolResponse, type HeadingStructureResponse, type KeywordFrequencyResponse, type ReadabilityResponse } from "./content-analysis-tool-contract";
class ContentAnalysisToolError extends Error { readonly code: string; constructor(message: string, code = "content_analysis_tool_error") { super(message); this.name = "ContentAnalysisToolError"; this.code = code; } }
async function runTool<T extends ContentAnalysisToolResponse>(endpoint: string, url: string, validator: (payload: unknown) => payload is T): Promise<T> { const response = await fetch(endpoint, { method: "POST", headers: { accept: "application/json", "content-type": "application/json" }, body: JSON.stringify({ url }) }); const payload: unknown = await response.json().catch(() => null); if (!response.ok) { if (isToolErrorPayload(payload)) throw new ContentAnalysisToolError(payload.detail.message, payload.detail.code); throw new ContentAnalysisToolError("Tool API request failed.", "tool_api_error"); } if (!validator(payload)) throw new ContentAnalysisToolError("Tool API returned an invalid result.", "tool_api_invalid_response"); return payload; }
export function headingStructureResultText(result: HeadingStructureResponse): string { return [`Final URL: ${result.final_url}`, `Headings: ${result.total_headings}`, `H1 count: ${result.h1_count}`, `Skipped levels: ${result.skipped_level_count}`, `Empty headings: ${result.empty_heading_count}`, `Recommendation: ${result.recommendation}`].join("\n"); }
export function keywordFrequencyResultText(result: KeywordFrequencyResponse): string { return [`Final URL: ${result.final_url}`, `Total words: ${result.total_words}`, `Unique terms: ${result.unique_terms}`, `Overused terms: ${result.overused_terms.length}`, `Recommendation: ${result.recommendation}`].join("\n"); }
export function readabilityResultText(result: ReadabilityResponse): string { return [`Final URL: ${result.final_url}`, `Words: ${result.word_count}`, `Sentences: ${result.sentence_count}`, `Readability score: ${result.readability_score}`, `Reading time: ${result.estimated_reading_time_minutes} min`, `Recommendation: ${result.recommendation}`].join("\n"); }
const dictionary = { ru: { url: "URL страницы", run: "Запустить анализ", loading: "Анализируем…", result: "Результат", recommendation: "Рекомендация", invalidUrl: "Введите корректный http(s) URL с доменом." }, en: { url: "Page URL", run: "Run analysis", loading: "Analyzing…", result: "Result", recommendation: "Recommendation", invalidUrl: "Enter a valid http(s) URL with a domain." } } as const;
function ErrorMessage({ value }: { value: string }) { return value ? <p className="tool-error" role="alert">{value}</p> : null; }
function Recommendation({ value, locale }: { value: string; locale: Locale }) { return <div className="tool-note"><strong>{dictionary[locale].recommendation}:</strong> {value}</div>; }
function BaseTool<T extends ContentAnalysisToolResponse>({ locale, endpoint, validator, render }: { locale: Locale; endpoint: string; validator: (payload: unknown) => payload is T; render: (result: T) => React.ReactNode }) { const [url, setUrl] = useState("https://example.com/"); const [result, setResult] = useState<T | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); async function onSubmit(event: FormEvent) { event.preventDefault(); const parsed = parseContentToolUrlInput(url); if (!parsed) { setError(dictionary[locale].invalidUrl); setResult(null); return; } setLoading(true); setError(""); try { setResult(await runTool(endpoint, parsed.toString(), validator)); } catch (caught) { setResult(null); setError(caught instanceof Error ? caught.message : "Tool failed."); } finally { setLoading(false); } } return <form className="tool-grid" onSubmit={onSubmit}><section className="tool-panel"><label className="field"><span>{dictionary[locale].url}</span><input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.com/" /></label><button className="button" type="submit" disabled={loading}>{loading ? dictionary[locale].loading : dictionary[locale].run}</button><ErrorMessage value={error} /></section>{result && <section className="tool-panel tool-panel-wide"><h2>{dictionary[locale].result}</h2>{render(result)}</section>}</form>; }
export function HeadingStructureTool({ locale }: { locale: Locale }) { return <BaseTool locale={locale} endpoint="/api/tools/heading-structure" validator={isHeadingStructureResponse} render={(result) => <><div className="result-grid"><article className="result-card"><h3>{locale === "ru" ? "Outline" : "Outline"}</h3><p className="calculated-value">{result.total_headings}</p><ul className="result-list"><li>H1: <strong>{result.h1_count}</strong></li><li>Skipped: <strong>{result.skipped_level_count}</strong></li><li>Empty: <strong>{result.empty_heading_count}</strong></li></ul></article></div><Recommendation value={result.recommendation} locale={locale} /></>} />; }
export function KeywordFrequencyTool({ locale }: { locale: Locale }) { return <BaseTool locale={locale} endpoint="/api/tools/keyword-density" validator={isKeywordFrequencyResponse} render={(result) => <><div className="result-grid"><article className="result-card"><h3>{locale === "ru" ? "Частотность" : "Frequency"}</h3><p className="calculated-value">{result.total_words}</p><ul className="result-list"><li>Unique: <strong>{result.unique_terms}</strong></li><li>Top words: <strong>{result.top_words.length}</strong></li><li>Overused: <strong>{result.overused_terms.length}</strong></li></ul></article></div><Recommendation value={result.recommendation} locale={locale} /></>} />; }
export function ReadabilityAnalyzerTool({ locale }: { locale: Locale }) { return <BaseTool locale={locale} endpoint="/api/tools/readability" validator={isReadabilityResponse} render={(result) => <><div className="result-grid"><article className="result-card"><h3>{locale === "ru" ? "Читабельность" : "Readability"}</h3><p className="calculated-value">{result.readability_score}</p><ul className="result-list"><li>Words: <strong>{result.word_count}</strong></li><li>Sentences: <strong>{result.sentence_count}</strong></li><li>Reading time: <strong>{result.estimated_reading_time_minutes} min</strong></li></ul></article></div><Recommendation value={result.recommendation} locale={locale} /></>} />; }
