export interface ToolApiErrorPayload { readonly detail: { readonly code: string; readonly message: string } }
export interface HeadingStructureResponse { readonly contract_version: "webdiag.tool.heading_structure.v1"; readonly generated_at: string; readonly requested_url: string; readonly final_url: string; readonly status_code: number; readonly scan_mode: "static_html_bounded"; readonly total_headings: number; readonly h1_count: number; readonly skipped_level_count: number; readonly empty_heading_count: number; readonly outline: readonly unknown[]; readonly checks: readonly unknown[]; readonly recommendation: string; }
export interface KeywordFrequencyResponse { readonly contract_version: "webdiag.tool.keyword_frequency.v1"; readonly generated_at: string; readonly requested_url: string; readonly final_url: string; readonly status_code: number; readonly scan_mode: "static_html_bounded"; readonly total_words: number; readonly unique_terms: number; readonly top_words: readonly unknown[]; readonly top_bigrams: readonly unknown[]; readonly top_trigrams: readonly unknown[]; readonly overused_terms: readonly unknown[]; readonly recommendation: string; }
export interface ReadabilityResponse { readonly contract_version: "webdiag.tool.readability.v1"; readonly generated_at: string; readonly requested_url: string; readonly final_url: string; readonly status_code: number; readonly scan_mode: "static_html_bounded"; readonly formula_scope: "multilingual_heuristic"; readonly word_count: number; readonly sentence_count: number; readonly paragraph_count: number; readonly long_sentence_count: number; readonly estimated_reading_time_minutes: number; readonly readability_score: number; readonly metrics: readonly unknown[]; readonly recommendation: string; }
export type ContentAnalysisToolResponse = HeadingStructureResponse | KeywordFrequencyResponse | ReadabilityResponse;
export function isRecord(value: unknown): value is Record<string, unknown> { return !!value && typeof value === "object" && !Array.isArray(value); }
export function isToolErrorPayload(payload: unknown): payload is ToolApiErrorPayload { return isRecord(payload) && isRecord(payload.detail) && typeof payload.detail.code === "string" && typeof payload.detail.message === "string"; }
export function isHeadingStructureResponse(payload: unknown): payload is HeadingStructureResponse { return isRecord(payload) && payload.contract_version === "webdiag.tool.heading_structure.v1" && typeof payload.generated_at === "string" && typeof payload.requested_url === "string" && typeof payload.final_url === "string" && typeof payload.status_code === "number" && payload.scan_mode === "static_html_bounded" && typeof payload.total_headings === "number" && typeof payload.h1_count === "number" && typeof payload.skipped_level_count === "number" && typeof payload.empty_heading_count === "number" && Array.isArray(payload.outline) && Array.isArray(payload.checks) && typeof payload.recommendation === "string"; }
export function isKeywordFrequencyResponse(payload: unknown): payload is KeywordFrequencyResponse { return isRecord(payload) && payload.contract_version === "webdiag.tool.keyword_frequency.v1" && typeof payload.generated_at === "string" && typeof payload.requested_url === "string" && typeof payload.final_url === "string" && typeof payload.status_code === "number" && payload.scan_mode === "static_html_bounded" && typeof payload.total_words === "number" && typeof payload.unique_terms === "number" && Array.isArray(payload.top_words) && Array.isArray(payload.top_bigrams) && Array.isArray(payload.top_trigrams) && Array.isArray(payload.overused_terms) && typeof payload.recommendation === "string"; }
export function isReadabilityResponse(payload: unknown): payload is ReadabilityResponse { return isRecord(payload) && payload.contract_version === "webdiag.tool.readability.v1" && typeof payload.generated_at === "string" && typeof payload.requested_url === "string" && typeof payload.final_url === "string" && typeof payload.status_code === "number" && payload.scan_mode === "static_html_bounded" && payload.formula_scope === "multilingual_heuristic" && typeof payload.word_count === "number" && typeof payload.sentence_count === "number" && typeof payload.paragraph_count === "number" && typeof payload.long_sentence_count === "number" && typeof payload.estimated_reading_time_minutes === "number" && typeof payload.readability_score === "number" && Array.isArray(payload.metrics) && typeof payload.recommendation === "string"; }
export function parseContentToolUrlInput(value: string): URL | null { try { const url = new URL(value.trim()); return url.protocol === "http:" || url.protocol === "https:" ? url : null; } catch { return null; } }
