"use client";
import { useState, type FormEvent } from "react";
import type { Locale } from "@webdiag/tool-registry";
import { isBrokenImageCheckerResponse, isBrokenLinkCheckerResponse, isLinkAnalyzerResponse, isToolErrorPayload, parseLinkToolUrlInput, type BrokenImageCheckerResponse, type BrokenLinkCheckerResponse, type LinkAnalyzerResponse, type LinkHealthToolResponse } from "./link-health-tool-contract";
class LinkHealthToolError extends Error { readonly code: string; constructor(message: string, code = "link_health_tool_error") { super(message); this.name = "LinkHealthToolError"; this.code = code; } }
async function runTool<T extends LinkHealthToolResponse>(endpoint: string, url: string, validator: (payload: unknown) => payload is T): Promise<T> { const response = await fetch(endpoint, { method: "POST", headers: { accept: "application/json", "content-type": "application/json" }, body: JSON.stringify({ url }) }); const payload: unknown = await response.json().catch(() => null); if (!response.ok) { if (isToolErrorPayload(payload)) throw new LinkHealthToolError(payload.detail.message, payload.detail.code); throw new LinkHealthToolError("Tool API request failed.", "tool_api_error"); } if (!validator(payload)) throw new LinkHealthToolError("Tool API returned an invalid result.", "tool_api_invalid_response"); return payload; }
export function linkAnalyzerResultText(result: LinkAnalyzerResponse): string { return [`Final URL: ${result.final_url}`, `Total links: ${result.total_links}`, `Internal: ${result.internal_count}`, `External: ${result.external_count}`, `target=_blank without noopener: ${result.target_blank_missing_noopener_count}`, `Recommendation: ${result.recommendation}`].join("\n"); }
export function brokenLinkResultText(result: BrokenLinkCheckerResponse): string { return [`Final URL: ${result.final_url}`, `Checked links: ${result.checked_link_count}/${result.discovered_link_count}`, `Broken links: ${result.broken_link_count}`, `Redirecting links: ${result.redirecting_link_count}`, `Recommendation: ${result.recommendation}`].join("\n"); }
export function brokenImageResultText(result: BrokenImageCheckerResponse): string { return [`Final URL: ${result.final_url}`, `Checked images: ${result.checked_image_count}/${result.discovered_image_count}`, `Broken images: ${result.broken_image_count}`, `Redirecting images: ${result.redirecting_image_count}`, `Recommendation: ${result.recommendation}`].join("\n"); }
const dictionary = { ru: { url: "URL страницы", run: "Запустить проверку", loading: "Проверяем…", result: "Результат", recommendation: "Рекомендация", invalidUrl: "Введите корректный http(s) URL с доменом." }, en: { url: "Page URL", run: "Run check", loading: "Checking…", result: "Result", recommendation: "Recommendation", invalidUrl: "Enter a valid http(s) URL with a domain." } } as const;
function UrlField({ url, setUrl, locale }: { url: string; setUrl: (value: string) => void; locale: Locale }) { return <label className="field"><span>{dictionary[locale].url}</span><input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.com/" /></label>; }
function ErrorMessage({ value }: { value: string }) { return value ? <p className="tool-error" role="alert">{value}</p> : null; }
function Recommendation({ value, locale }: { value: string; locale: Locale }) { return <div className="tool-note"><strong>{dictionary[locale].recommendation}:</strong> {value}</div>; }
function BaseTool<T extends LinkHealthToolResponse>({ locale, endpoint, validator, render }: { locale: Locale; endpoint: string; validator: (payload: unknown) => payload is T; render: (result: T) => React.ReactNode }) { const [url, setUrl] = useState("https://example.com/"); const [result, setResult] = useState<T | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); async function onSubmit(event: FormEvent) { event.preventDefault(); const parsed = parseLinkToolUrlInput(url); if (!parsed) { setError(dictionary[locale].invalidUrl); setResult(null); return; } setLoading(true); setError(""); try { setResult(await runTool(endpoint, parsed.toString(), validator)); } catch (caught) { setResult(null); setError(caught instanceof Error ? caught.message : "Tool failed."); } finally { setLoading(false); } } return <form className="tool-grid" onSubmit={onSubmit}><section className="tool-panel"><UrlField url={url} setUrl={setUrl} locale={locale} /><button className="button" type="submit" disabled={loading}>{loading ? dictionary[locale].loading : dictionary[locale].run}</button><ErrorMessage value={error} /></section>{result && <section className="tool-panel tool-panel-wide"><h2>{dictionary[locale].result}</h2>{render(result)}</section>}</form>; }
export function LinkAnalyzerTool({ locale }: { locale: Locale }) { return <BaseTool locale={locale} endpoint="/api/tools/link-analyzer" validator={isLinkAnalyzerResponse} render={(result) => <><div className="result-grid"><article className="result-card"><h3>{locale === "ru" ? "Структура" : "Structure"}</h3><p className="calculated-value">{result.total_links}</p><ul className="result-list"><li>Internal: <strong>{result.internal_count}</strong></li><li>External: <strong>{result.external_count}</strong></li><li>Missing noopener: <strong>{result.target_blank_missing_noopener_count}</strong></li></ul></article></div><Recommendation value={result.recommendation} locale={locale} /></>} />; }
export function BrokenLinkCheckerTool({ locale }: { locale: Locale }) { return <BaseTool locale={locale} endpoint="/api/tools/broken-links" validator={isBrokenLinkCheckerResponse} render={(result) => <><div className="result-grid"><article className="result-card"><h3>{locale === "ru" ? "Доступность" : "Availability"}</h3><p className="calculated-value">{result.broken_link_count}</p><ul className="result-list"><li>Checked: <strong>{result.checked_link_count}</strong></li><li>Redirects: <strong>{result.redirecting_link_count}</strong></li></ul></article></div><Recommendation value={result.recommendation} locale={locale} /></>} />; }
export function BrokenImageCheckerTool({ locale }: { locale: Locale }) { return <BaseTool locale={locale} endpoint="/api/tools/broken-images" validator={isBrokenImageCheckerResponse} render={(result) => <><div className="result-grid"><article className="result-card"><h3>{locale === "ru" ? "Изображения" : "Images"}</h3><p className="calculated-value">{result.broken_image_count}</p><ul className="result-list"><li>Checked: <strong>{result.checked_image_count}</strong></li><li>Redirects: <strong>{result.redirecting_image_count}</strong></li></ul></article></div><Recommendation value={result.recommendation} locale={locale} /></>} />; }
