export interface ToolApiErrorPayload { readonly detail: { readonly code: string; readonly message: string } }
export interface LinkAnalyzerResponse { readonly contract_version: "webdiag.tool.link_analyzer.v1"; readonly generated_at: string; readonly requested_url: string; readonly final_url: string; readonly status_code: number; readonly scan_mode: "static_html_bounded"; readonly total_links: number; readonly unique_http_links: number; readonly internal_count: number; readonly external_count: number; readonly same_page_count: number; readonly mailto_tel_count: number; readonly non_http_count: number; readonly nofollow_count: number; readonly sponsored_count: number; readonly ugc_count: number; readonly target_blank_missing_noopener_count: number; readonly sample_links: readonly unknown[]; readonly recommendation: string; }
export interface BrokenLinkCheckerResponse { readonly contract_version: "webdiag.tool.broken_link_checker.v1"; readonly generated_at: string; readonly requested_url: string; readonly final_url: string; readonly status_code: number; readonly scan_mode: "static_html_bounded"; readonly discovered_link_count: number; readonly checked_link_count: number; readonly broken_link_count: number; readonly redirecting_link_count: number; readonly skipped_non_http_count: number; readonly items: readonly unknown[]; readonly recommendation: string; }
export interface BrokenImageCheckerResponse { readonly contract_version: "webdiag.tool.broken_image_checker.v1"; readonly generated_at: string; readonly requested_url: string; readonly final_url: string; readonly status_code: number; readonly scan_mode: "static_html_bounded"; readonly discovered_image_count: number; readonly checked_image_count: number; readonly broken_image_count: number; readonly redirecting_image_count: number; readonly items: readonly unknown[]; readonly recommendation: string; }
export type LinkHealthToolResponse = LinkAnalyzerResponse | BrokenLinkCheckerResponse | BrokenImageCheckerResponse;
export function isRecord(value: unknown): value is Record<string, unknown> { return !!value && typeof value === "object" && !Array.isArray(value); }
export function isToolErrorPayload(payload: unknown): payload is ToolApiErrorPayload { return isRecord(payload) && isRecord(payload.detail) && typeof payload.detail.code === "string" && typeof payload.detail.message === "string"; }
export function isLinkAnalyzerResponse(payload: unknown): payload is LinkAnalyzerResponse { return isRecord(payload) && payload.contract_version === "webdiag.tool.link_analyzer.v1" && typeof payload.generated_at === "string" && typeof payload.requested_url === "string" && typeof payload.final_url === "string" && typeof payload.status_code === "number" && payload.scan_mode === "static_html_bounded" && typeof payload.total_links === "number" && typeof payload.unique_http_links === "number" && typeof payload.internal_count === "number" && typeof payload.external_count === "number" && typeof payload.same_page_count === "number" && typeof payload.mailto_tel_count === "number" && typeof payload.non_http_count === "number" && typeof payload.nofollow_count === "number" && typeof payload.sponsored_count === "number" && typeof payload.ugc_count === "number" && typeof payload.target_blank_missing_noopener_count === "number" && Array.isArray(payload.sample_links) && typeof payload.recommendation === "string"; }
export function isBrokenLinkCheckerResponse(payload: unknown): payload is BrokenLinkCheckerResponse { return isRecord(payload) && payload.contract_version === "webdiag.tool.broken_link_checker.v1" && typeof payload.generated_at === "string" && typeof payload.requested_url === "string" && typeof payload.final_url === "string" && typeof payload.status_code === "number" && payload.scan_mode === "static_html_bounded" && typeof payload.discovered_link_count === "number" && typeof payload.checked_link_count === "number" && typeof payload.broken_link_count === "number" && typeof payload.redirecting_link_count === "number" && typeof payload.skipped_non_http_count === "number" && Array.isArray(payload.items) && typeof payload.recommendation === "string"; }
export function isBrokenImageCheckerResponse(payload: unknown): payload is BrokenImageCheckerResponse { return isRecord(payload) && payload.contract_version === "webdiag.tool.broken_image_checker.v1" && typeof payload.generated_at === "string" && typeof payload.requested_url === "string" && typeof payload.final_url === "string" && typeof payload.status_code === "number" && payload.scan_mode === "static_html_bounded" && typeof payload.discovered_image_count === "number" && typeof payload.checked_image_count === "number" && typeof payload.broken_image_count === "number" && typeof payload.redirecting_image_count === "number" && Array.isArray(payload.items) && typeof payload.recommendation === "string"; }
export function parseLinkToolUrlInput(value: string): URL | null { try { const url = new URL(value.trim()); return url.protocol === "http:" || url.protocol === "https:" ? url : null; } catch { return null; } }
