import { toolPage } from "./shared";

export const developmentDataToolPages = [
  toolPage({
    slug: "json-formatter-validator",
    seoTitle: { ru: "JSON Formatter и проверка JSON онлайн", en: "JSON Formatter & Validator Online" },
    metaDescription: { ru: "Проверьте синтаксис JSON и отформатируйте корректные данные с отступом в 2 пробела. Обработка выполняется локально в браузере.", en: "Validate JSON syntax and format valid data with two-space indentation. Processing runs locally in your browser." },
    h1: { ru: "Форматирование и проверка JSON онлайн", en: "JSON Formatter & Validator Online" },
    lead: { ru: "Вставьте JSON, чтобы проверить синтаксис и получить читаемую структуру с отступами.", en: "Paste JSON to validate its syntax and produce a readable, indented structure." },
    quickFacts: [
      { ru: "Стандартный JSON", en: "Standard JSON" },
      { ru: "Отступ в 2 пробела", en: "Two-space indentation" },
      { ru: "Локальная обработка", en: "Local processing" },
    ],
    howToSteps: [
      { ru: "Вставьте JSON в поле ввода.", en: "Paste JSON into the input field." },
      { ru: "Нажмите кнопку форматирования.", en: "Select the format action." },
      { ru: "Скопируйте результат или исправьте указанную синтаксическую ошибку.", en: "Copy the result or correct the reported syntax error." },
    ],
    supportedFeatures: [
      { ru: "Проверка через стандартный JSON parser браузера.", en: "Validation with the browser's standard JSON parser." },
      { ru: "Форматирование объектов, массивов, строк, чисел, boolean и null.", en: "Formatting for objects, arrays, strings, numbers, booleans, and null." },
      { ru: "Сообщение об ошибке для некорректного синтаксиса.", en: "An error message for invalid syntax." },
    ],
    limitations: [
      { ru: "Инструмент не восстанавливает повреждённый JSON автоматически.", en: "The tool does not automatically repair malformed JSON." },
      { ru: "Нет tree view, minify и преобразования JSON5.", en: "Tree view, minification, and JSON5 conversion are not included." },
    ],
    useCases: [
      { ru: "Проверка ответа API перед отладкой.", en: "Checking an API response before debugging." },
      { ru: "Подготовка конфигурационного файла к просмотру.", en: "Making a configuration file easier to review." },
      { ru: "Поиск пропущенной запятой, кавычки или скобки.", en: "Finding a missing comma, quote, or bracket." },
    ],
    technicalNotes: [
      { ru: "Результат создаётся с помощью JSON.parse и JSON.stringify.", en: "Output is produced with JSON.parse and JSON.stringify." },
      { ru: "Порядок ключей сохраняется в пределах поведения JavaScript parser.", en: "Key order follows JavaScript parser behavior." },
    ],
    faq: [
      { question: { ru: "Поддерживается JSON5?", en: "Does it support JSON5?" }, answer: { ru: "Нет. Ввод должен соответствовать стандартному синтаксису JSON.", en: "No. Input must follow standard JSON syntax." } },
      { question: { ru: "Данные загружаются на сервер?", en: "Is the JSON uploaded?" }, answer: { ru: "Нет. Проверка и форматирование выполняются в браузере.", en: "No. Validation and formatting run in the browser." } },
    ],
    relatedToolSlugs: ["base64-converter", "url-encoder-decoder", "hash-generator"],
    sourceUrls: ["https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/JSON"],
  }),
  toolPage({
    slug: "url-encoder-decoder",
    seoTitle: { ru: "URL Encoder и Decoder онлайн", en: "URL Component Encoder & Decoder Online" },
    metaDescription: { ru: "Кодируйте и декодируйте текст для URL с помощью encodeURIComponent и decodeURIComponent прямо в браузере.", en: "Encode and decode text for URLs with encodeURIComponent and decodeURIComponent directly in your browser." },
    h1: { ru: "Кодирование и декодирование URL-компонентов", en: "URL Component Encoder & Decoder" },
    lead: { ru: "Преобразуйте текст в percent-encoded форму для query, path segment или другого компонента URL и восстановите исходное значение.", en: "Convert text to percent-encoded form for a query, path segment, or another URL component, and restore the original value." },
    quickFacts: [
      { ru: "UTF-8 текст", en: "UTF-8 text" },
      { ru: "Percent encoding", en: "Percent encoding" },
      { ru: "Локально в браузере", en: "Runs locally" },
    ],
    howToSteps: [
      { ru: "Введите текст или закодированную строку.", en: "Enter plain text or an encoded string." },
      { ru: "Выберите кодирование или декодирование.", en: "Choose encode or decode." },
      { ru: "Скопируйте преобразованное значение.", en: "Copy the transformed value." },
    ],
    supportedFeatures: [
      { ru: "Кодирование через encodeURIComponent.", en: "Encoding with encodeURIComponent." },
      { ru: "Декодирование через decodeURIComponent.", en: "Decoding with decodeURIComponent." },
      { ru: "Поддержка Unicode-текста.", en: "Unicode text support." },
    ],
    limitations: [
      { ru: "Это не анализатор полного URL и не проверка доступности адреса.", en: "This is not a full URL parser or availability checker." },
      { ru: "Некорректная percent-последовательность возвращает ошибку.", en: "Malformed percent sequences return an error." },
    ],
    useCases: [
      { ru: "Подготовка значения query parameter.", en: "Preparing a query-parameter value." },
      { ru: "Проверка закодированной строки из логов.", en: "Inspecting an encoded value from logs." },
      { ru: "Безопасная передача пробелов и специальных символов.", en: "Representing spaces and special characters safely." },
    ],
    technicalNotes: [
      { ru: "Пробел кодируется как %20, а не как плюс.", en: "A space is encoded as %20, not as a plus sign." },
      { ru: "Инструмент работает с компонентом URL, а не со всей строкой адреса целиком.", en: "The tool targets a URL component rather than a complete URL string." },
    ],
    faq: [
      { question: { ru: "Можно вставить полный URL?", en: "Can I paste a complete URL?" }, answer: { ru: "Можно, но будет закодирована вся строка как единый компонент. Для точной работы обычно кодируют только нужное значение.", en: "Yes, but the whole string will be encoded as one component. Usually only the intended value should be encoded." } },
      { question: { ru: "Чем это отличается от Base64?", en: "How is this different from Base64?" }, answer: { ru: "URL encoding экранирует символы для URL, а Base64 представляет байты в текстовом алфавите.", en: "URL encoding escapes characters for URLs, while Base64 represents bytes with a text alphabet." } },
    ],
    relatedToolSlugs: ["base64-converter", "json-formatter-validator", "hash-generator"],
    sourceUrls: ["https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent"],
  }),
  toolPage({
    slug: "base64-converter",
    seoTitle: { ru: "Base64 Encoder и Decoder для текста", en: "Base64 Text Encoder & Decoder Online" },
    metaDescription: { ru: "Кодируйте UTF-8 текст в Base64 и декодируйте Base64 обратно в текст прямо в браузере.", en: "Encode UTF-8 text as Base64 and decode Base64 back to text directly in your browser." },
    h1: { ru: "Кодирование и декодирование Base64 для текста", en: "Base64 Text Encoder & Decoder" },
    lead: { ru: "Преобразуйте UTF-8 текст в Base64 или восстановите исходную строку из корректного Base64-значения.", en: "Convert UTF-8 text to Base64 or restore the original string from a valid Base64 value." },
    quickFacts: [
      { ru: "UTF-8 текст", en: "UTF-8 text" },
      { ru: "Encode и decode", en: "Encode and decode" },
      { ru: "Не является шифрованием", en: "Not encryption" },
    ],
    howToSteps: [
      { ru: "Введите обычный текст или Base64-строку.", en: "Enter plain text or a Base64 string." },
      { ru: "Выберите нужное направление преобразования.", en: "Choose the conversion direction." },
      { ru: "Скопируйте результат.", en: "Copy the result." },
    ],
    supportedFeatures: [
      { ru: "Кодирование Unicode-текста через UTF-8 байты.", en: "Unicode text encoding through UTF-8 bytes." },
      { ru: "Игнорирование пробельных символов при декодировании.", en: "Whitespace is ignored during decoding." },
      { ru: "Ошибка при некорректной Base64-строке или невалидном UTF-8 результате.", en: "Errors for invalid Base64 or invalid UTF-8 output." },
    ],
    limitations: [
      { ru: "Файлы и изображения не поддерживаются.", en: "Files and images are not supported." },
      { ru: "URL-safe Base64 без символов + и / не преобразуется автоматически.", en: "URL-safe Base64 using alternatives to + and / is not normalized automatically." },
    ],
    useCases: [
      { ru: "Просмотр текстового payload.", en: "Inspecting a text payload." },
      { ru: "Подготовка тестовых данных для API.", en: "Preparing test data for an API." },
      { ru: "Проверка сохранённого Base64-значения.", en: "Checking a stored Base64 value." },
    ],
    technicalNotes: [
      { ru: "Base64 увеличивает объём данных примерно на треть и не скрывает содержимое.", en: "Base64 typically increases data size by roughly one third and does not conceal content." },
      { ru: "Декодированный набор байтов должен быть корректным UTF-8 текстом.", en: "Decoded bytes must form valid UTF-8 text." },
    ],
    faq: [
      { question: { ru: "Base64 защищает пароль?", en: "Does Base64 protect a password?" }, answer: { ru: "Нет. Base64 легко декодируется и не должен использоваться как защита секретов.", en: "No. Base64 is easily decoded and should not be used to protect secrets." } },
      { question: { ru: "Можно кодировать изображение?", en: "Can it encode an image?" }, answer: { ru: "Текущая версия работает только с текстом.", en: "The current version works with text only." } },
    ],
    relatedToolSlugs: ["url-encoder-decoder", "json-formatter-validator", "hash-generator"],
    sourceUrls: ["https://developer.mozilla.org/docs/Glossary/Base64"],
  }),
  toolPage({
    slug: "hash-generator",
    seoTitle: { ru: "Генератор SHA-256, SHA-384 и SHA-512", en: "SHA-256, SHA-384 & SHA-512 Hash Generator" },
    metaDescription: { ru: "Вычислите SHA-256, SHA-384 или SHA-512 для введённого текста через Web Crypto API прямо в браузере.", en: "Calculate SHA-256, SHA-384, or SHA-512 for entered text with the Web Crypto API directly in your browser." },
    h1: { ru: "Генератор SHA-хешей для текста", en: "SHA Hash Generator for Text" },
    lead: { ru: "Получите шестнадцатеричный SHA-256, SHA-384 или SHA-512 digest для строки без отправки текста на сервер.", en: "Generate a hexadecimal SHA-256, SHA-384, or SHA-512 digest for a string without sending the text to a server." },
    quickFacts: [
      { ru: "SHA-256 / 384 / 512", en: "SHA-256 / 384 / 512" },
      { ru: "UTF-8 вход", en: "UTF-8 input" },
      { ru: "Web Crypto API", en: "Web Crypto API" },
    ],
    howToSteps: [
      { ru: "Введите текст.", en: "Enter text." },
      { ru: "Выберите SHA-алгоритм.", en: "Select a SHA algorithm." },
      { ru: "Сгенерируйте и скопируйте hex digest.", en: "Generate and copy the hexadecimal digest." },
    ],
    supportedFeatures: [
      { ru: "SHA-256, SHA-384 и SHA-512.", en: "SHA-256, SHA-384, and SHA-512." },
      { ru: "Кодирование входной строки как UTF-8.", en: "UTF-8 encoding for the input string." },
      { ru: "Нижний регистр шестнадцатеричного результата.", en: "Lowercase hexadecimal output." },
    ],
    limitations: [
      { ru: "Нет MD5, SHA-1, HMAC и хеширования файлов.", en: "MD5, SHA-1, HMAC, and file hashing are not included." },
      { ru: "Хеш необратим и не является шифрованием.", en: "A hash is one-way and is not encryption." },
    ],
    useCases: [
      { ru: "Сравнение контрольных значений текста.", en: "Comparing checksums for text." },
      { ru: "Подготовка тестового digest для разработки.", en: "Preparing a test digest during development." },
      { ru: "Проверка, изменилось ли строковое значение.", en: "Checking whether a string value changed." },
    ],
    technicalNotes: [
      { ru: "Одинаковый текст и алгоритм дают одинаковый digest.", en: "The same text and algorithm produce the same digest." },
      { ru: "Даже небольшое изменение входа существенно меняет результат.", en: "Even a small input change substantially changes the output." },
    ],
    faq: [
      { question: { ru: "Можно восстановить текст из хеша?", en: "Can the text be recovered from the hash?" }, answer: { ru: "Нет. Криптографический hash рассчитан как одностороннее преобразование.", en: "No. A cryptographic hash is designed as a one-way transformation." } },
      { question: { ru: "Можно хешировать файл?", en: "Can it hash a file?" }, answer: { ru: "Нет. Текущая версия принимает только текст.", en: "No. The current version accepts text only." } },
    ],
    relatedToolSlugs: ["base64-converter", "uuid-generator", "ulid-generator"],
    sourceUrls: ["https://developer.mozilla.org/docs/Web/API/SubtleCrypto/digest"],
  }),
  toolPage({
    slug: "uuid-generator",
    seoTitle: { ru: "Генератор UUID v4 онлайн", en: "UUID v4 Generator Online" },
    metaDescription: { ru: "Создайте случайный UUID версии 4 через криптографический генератор браузера. Один новый идентификатор за действие.", en: "Generate a random UUID version 4 with the browser cryptographic generator. One new identifier per action." },
    h1: { ru: "Генератор UUID v4 онлайн", en: "UUID v4 Generator Online" },
    lead: { ru: "Создайте стандартный UUID версии 4 для тестовых данных, записей и распределённых идентификаторов.", en: "Create a standard UUID version 4 for test data, records, and distributed identifiers." },
    quickFacts: [
      { ru: "UUID v4", en: "UUID v4" },
      { ru: "Криптографическая случайность", en: "Cryptographic randomness" },
      { ru: "Один идентификатор", en: "One identifier" },
    ],
    howToSteps: [
      { ru: "Нажмите кнопку генерации.", en: "Select the generate action." },
      { ru: "Скопируйте полученный UUID.", en: "Copy the generated UUID." },
      { ru: "Повторите действие, если нужен новый идентификатор.", en: "Repeat the action when you need another identifier." },
    ],
    supportedFeatures: [
      { ru: "Стандартный формат 8-4-4-4-12.", en: "Standard 8-4-4-4-12 format." },
      { ru: "Генерация через crypto.randomUUID.", en: "Generation through crypto.randomUUID." },
      { ru: "Быстрое копирование результата.", en: "Quick result copying." },
    ],
    limitations: [
      { ru: "Нет пакетной генерации и проверки UUID.", en: "Bulk generation and UUID validation are not included." },
      { ru: "Другие версии UUID, включая v1 и v7, не поддерживаются.", en: "Other UUID versions, including v1 and v7, are not supported." },
    ],
    useCases: [
      { ru: "Идентификаторы тестовых записей.", en: "Identifiers for test records." },
      { ru: "Mock data и fixtures.", en: "Mock data and fixtures." },
      { ru: "Создание независимого client-side ID.", en: "Creating an independent client-side ID." },
    ],
    technicalNotes: [
      { ru: "UUID v4 не содержит временную метку и не сортируется по времени.", en: "UUID v4 does not contain a timestamp and is not time-sortable." },
      { ru: "Уникальность вероятностная, а не результат проверки общей базы.", en: "Uniqueness is probabilistic rather than checked against a global database." },
    ],
    faq: [
      { question: { ru: "UUID гарантированно уникален?", en: "Is a UUID guaranteed to be unique?" }, answer: { ru: "Абсолютной глобальной гарантии нет, но пространство UUID v4 делает случайное совпадение крайне маловероятным.", en: "There is no absolute global guarantee, but the UUID v4 space makes a random collision extremely unlikely." } },
      { question: { ru: "Чем UUID отличается от ULID?", en: "How does UUID differ from ULID?" }, answer: { ru: "UUID v4 полностью случайный, а ULID включает время и лексикографически сортируется.", en: "UUID v4 is random, while ULID includes time and sorts lexicographically." } },
    ],
    relatedToolSlugs: ["ulid-generator", "hash-generator", "unix-timestamp-converter"],
    sourceUrls: ["https://developer.mozilla.org/docs/Web/API/Crypto/randomUUID"],
  }),
  toolPage({
    slug: "unix-timestamp-converter",
    seoTitle: { ru: "Конвертер Unix timestamp и ISO 8601", en: "Unix Timestamp & ISO 8601 Converter" },
    metaDescription: { ru: "Преобразуйте Unix timestamp в секундах в UTC ISO 8601 и дату обратно в Unix seconds прямо в браузере.", en: "Convert a Unix timestamp in seconds to UTC ISO 8601 and a date back to Unix seconds directly in your browser." },
    h1: { ru: "Конвертер Unix timestamp и ISO 8601", en: "Unix Timestamp & ISO 8601 Converter" },
    lead: { ru: "Преобразуйте количество секунд от Unix epoch в UTC-дату ISO 8601 или выполните обратное преобразование.", en: "Convert seconds since the Unix epoch to a UTC ISO 8601 date or perform the reverse conversion." },
    quickFacts: [
      { ru: "Unix seconds", en: "Unix seconds" },
      { ru: "UTC ISO 8601", en: "UTC ISO 8601" },
      { ru: "Два направления", en: "Two-way conversion" },
    ],
    howToSteps: [
      { ru: "Введите Unix timestamp в секундах или дату.", en: "Enter Unix seconds or a date value." },
      { ru: "Выберите нужное направление.", en: "Choose the conversion direction." },
      { ru: "Скопируйте ISO-строку или целое число секунд.", en: "Copy the ISO string or integer number of seconds." },
    ],
    supportedFeatures: [
      { ru: "Unix timestamp в секундах.", en: "Unix timestamps in seconds." },
      { ru: "Результат даты в UTC через toISOString.", en: "UTC date output through toISOString." },
      { ru: "Разбор корректных значений даты, поддерживаемых браузером.", en: "Parsing of valid date values supported by the browser." },
    ],
    limitations: [
      { ru: "Миллисекунды не определяются автоматически.", en: "Milliseconds are not detected automatically." },
      { ru: "Нет выбора часового пояса или форматирования локального времени.", en: "Timezone selection and localized display are not included." },
    ],
    useCases: [
      { ru: "Чтение временной метки из API или лога.", en: "Reading a timestamp from an API or log." },
      { ru: "Подготовка секунд Unix для теста.", en: "Preparing Unix seconds for a test." },
      { ru: "Проверка UTC-момента события.", en: "Checking the UTC instant of an event." },
    ],
    technicalNotes: [
      { ru: "Unix epoch начинается 1 января 1970 года в UTC.", en: "The Unix epoch starts on January 1, 1970 UTC." },
      { ru: "При преобразовании даты дробные секунды отбрасываются вниз до целого Unix timestamp.", en: "When converting a date, fractional seconds are floored to an integer Unix timestamp." },
    ],
    faq: [
      { question: { ru: "Timestamp должен быть в секундах?", en: "Should the timestamp use seconds?" }, answer: { ru: "Да. Текущая версия ожидает секунды, а не миллисекунды.", en: "Yes. The current version expects seconds, not milliseconds." } },
      { question: { ru: "Можно выбрать часовой пояс?", en: "Can I select a timezone?" }, answer: { ru: "Нет. ISO-результат показывается в UTC.", en: "No. ISO output is displayed in UTC." } },
    ],
    relatedToolSlugs: ["ulid-generator", "uuid-generator", "json-formatter-validator"],
    sourceUrls: ["https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Date"],
  }),
  toolPage({
    slug: "ulid-generator",
    seoTitle: { ru: "Генератор ULID онлайн", en: "ULID Generator Online" },
    metaDescription: { ru: "Создайте стандартный 26-символьный ULID с временной и криптографически случайной частью прямо в браузере.", en: "Generate a standard 26-character ULID with time and cryptographically random components directly in your browser." },
    h1: { ru: "Генератор ULID онлайн", en: "ULID Generator Online" },
    lead: { ru: "Создайте лексикографически сортируемый идентификатор, состоящий из временной метки и случайной части Crockford Base32.", en: "Create a lexicographically sortable identifier built from a timestamp and Crockford Base32 randomness." },
    quickFacts: [
      { ru: "26 символов", en: "26 characters" },
      { ru: "Сортировка по времени", en: "Time-sortable" },
      { ru: "Crockford Base32", en: "Crockford Base32" },
    ],
    howToSteps: [
      { ru: "Нажмите кнопку генерации.", en: "Select the generate action." },
      { ru: "Скопируйте 26-символьный ULID.", en: "Copy the 26-character ULID." },
      { ru: "Повторите для следующего значения.", en: "Repeat for another value." },
    ],
    supportedFeatures: [
      { ru: "48-битная временная часть в миллисекундах.", en: "A 48-bit millisecond timestamp component." },
      { ru: "80 бит случайных данных из crypto.getRandomValues.", en: "80 bits of randomness from crypto.getRandomValues." },
      { ru: "Алфавит Crockford Base32 без неоднозначных символов.", en: "Crockford Base32 without ambiguous characters." },
    ],
    limitations: [
      { ru: "Нет пакетной генерации и разбора ULID.", en: "Bulk generation and ULID parsing are not included." },
      { ru: "Генератор не реализует monotonic ULID для нескольких значений в одну миллисекунду.", en: "The generator does not implement monotonic ULIDs for multiple values within the same millisecond." },
    ],
    useCases: [
      { ru: "Сортируемые идентификаторы записей.", en: "Sortable record identifiers." },
      { ru: "Логи и события, где полезен временной порядок.", en: "Logs and events where time ordering is useful." },
      { ru: "Тестовые данные для систем с ULID.", en: "Test data for systems that use ULIDs." },
    ],
    technicalNotes: [
      { ru: "Первые десять символов кодируют время, оставшиеся шестнадцать — случайность.", en: "The first ten characters encode time and the remaining sixteen encode randomness." },
      { ru: "ULID можно сортировать как строку при одинаковом регистре.", en: "ULIDs can be sorted as strings when casing is consistent." },
    ],
    faq: [
      { question: { ru: "Чем ULID отличается от UUID v4?", en: "How does ULID differ from UUID v4?" }, answer: { ru: "ULID содержит временную часть и сортируется по времени, а UUID v4 состоит из случайных данных.", en: "ULID contains a time component and sorts by time, while UUID v4 is random." } },
      { question: { ru: "Можно извлечь дату из результата?", en: "Can the date be extracted?" }, answer: { ru: "В формате ULID временная часть присутствует, но текущий инструмент генерирует значение и не выполняет его разбор.", en: "ULID contains a timestamp component, but the current tool generates values and does not parse them." } },
    ],
    relatedToolSlugs: ["uuid-generator", "unix-timestamp-converter", "hash-generator"],
    sourceUrls: ["https://github.com/ulid/spec"],
  }),

  toolPage({
    slug: "jsonpath-tester",
    seoTitle: { ru: "JSONPath Tester и Query Lab онлайн", en: "JSONPath Tester & Query Lab Online" },
    metaDescription: { ru: "Выполняйте bounded JSONPath-запросы по локальному JSON: properties, indices, wildcards, recursive descent, unions, slices и простые filters без eval.", en: "Run bounded JSONPath queries against local JSON with properties, indices, wildcards, recursive descent, unions, slices, and simple filters without eval." },
    h1: { ru: "JSONPath Query Lab", en: "JSONPath Query Lab" },
    lead: { ru: "Проверяйте JSONPath выражения и получайте bounded список совпадений с JSON Pointer paths без выполнения JavaScript-кода.", en: "Test JSONPath expressions and receive a bounded match list with JSON Pointer paths without executing JavaScript code." },
    quickFacts: [
      { ru: "Локальный JSON", en: "Local JSON" },
      { ru: "Без eval", en: "No eval" },
      { ru: "До 500 совпадений", en: "Up to 500 matches" },
    ],
    howToSteps: [
      { ru: "Вставьте JSON-документ.", en: "Paste a JSON document." },
      { ru: "Введите JSONPath, начинающийся с $.", en: "Enter a JSONPath expression starting with $." },
      { ru: "Запустите запрос и изучите paths и значения совпадений.", en: "Run the query and inspect match paths and values." },
    ],
    supportedFeatures: [
      { ru: "Dot и bracket properties, array indices и negative indices.", en: "Dot and bracket properties, array indices, and negative indices." },
      { ru: "Wildcards, recursive descent, unions и array slices.", en: "Wildcards, recursive descent, unions, and array slices." },
      { ru: "Existence и comparison filters с string, number, boolean и null literals.", en: "Existence and comparison filters using string, number, boolean, and null literals." },
      { ru: "JSON Pointer paths для каждого совпадения и дедупликация по path.", en: "JSON Pointer paths for every match and path-based deduplication." },
    ],
    limitations: [
      { ru: "Поддерживается документированный subset JSONPath, а не каждый vendor-specific extension.", en: "A documented JSONPath subset is supported rather than every vendor-specific extension." },
      { ru: "Script expressions, functions, arithmetic, regular expressions и eval не выполняются.", en: "Script expressions, functions, arithmetic, regular expressions, and eval are not executed." },
      { ru: "Ввод ограничен 500 000 символов, 10 000 узлов и глубиной 64; результат — 500 совпадений.", en: "Input is limited to 500,000 characters, 10,000 nodes, and depth 64; output is limited to 500 matches." },
    ],
    useCases: [
      { ru: "Проверка path для API response или fixture.", en: "Testing a path against an API response or fixture." },
      { ru: "Поиск вложенных properties без написания скрипта.", en: "Finding nested properties without writing a script." },
      { ru: "Подготовка bounded JSONPath выражения для интеграции.", en: "Preparing a bounded JSONPath expression for an integration." },
    ],
    technicalNotes: [
      { ru: "Parser не использует Function, eval или JavaScript expression execution.", en: "The parser does not use Function, eval, or JavaScript expression execution." },
      { ru: "Traversal ограничен 10 000 посещёнными узлами и останавливается с явной ошибкой при превышении.", en: "Traversal is bounded to 10,000 visited nodes and stops with an explicit error when exceeded." },
    ],
    faq: [
      { question: { ru: "Поддерживаются filters?", en: "Are filters supported?" }, answer: { ru: "Да, но только existence и простые сравнения через ==, !=, <, <=, > и >=. JavaScript expressions и regex не выполняются.", en: "Yes, but only existence checks and simple comparisons using ==, !=, <, <=, >, and >=. JavaScript expressions and regex are not executed." } },
      { question: { ru: "Загружается ли JSON на сервер?", en: "Is the JSON uploaded?" }, answer: { ru: "Нет. Parsing и query выполняются локально в браузере.", en: "No. Parsing and querying run locally in the browser." } },
    ],
    relatedToolSlugs: ["json-formatter-validator", "json-schema-validator", "yaml-json-converter"],
    sourceUrls: ["https://www.rfc-editor.org/rfc/rfc9535.html"],
  }),
  toolPage({
    slug: "toml-json-converter",
    seoTitle: { ru: "TOML в JSON и JSON в TOML онлайн", en: "TOML to JSON & JSON to TOML Converter" },
    metaDescription: { ru: "Преобразуйте bounded TOML configuration subset и JSON локально: tables, array tables, dotted keys, arrays и inline tables с явными type limits.", en: "Convert a bounded TOML configuration subset and JSON locally with tables, array tables, dotted keys, arrays, inline tables, and explicit type limits." },
    h1: { ru: "TOML ↔ JSON Converter", en: "TOML ↔ JSON Converter" },
    lead: { ru: "Преобразуйте типичные TOML configuration documents в JSON и обратно без внешних запросов и скрытого object construction.", en: "Convert common TOML configuration documents to JSON and back without external requests or hidden object construction." },
    quickFacts: [
      { ru: "Два направления", en: "Two-way conversion" },
      { ru: "TOML tables", en: "TOML tables" },
      { ru: "До 5 000 узлов", en: "Up to 5,000 nodes" },
    ],
    howToSteps: [
      { ru: "Выберите TOML → JSON или JSON → TOML.", en: "Choose TOML → JSON or JSON → TOML." },
      { ru: "Вставьте configuration document.", en: "Paste the configuration document." },
      { ru: "Запустите conversion и проверьте warnings и результат.", en: "Run conversion and review warnings and output." },
    ],
    supportedFeatures: [
      { ru: "Basic и literal strings, booleans, safe integers, finite floats и arrays.", en: "Basic and literal strings, booleans, safe integers, finite floats, and arrays." },
      { ru: "Tables, dotted keys, array tables и inline tables.", en: "Tables, dotted keys, array tables, and inline tables." },
      { ru: "Hex, octal и binary integers с проверкой JSON safe-integer range.", en: "Hexadecimal, octal, and binary integers checked against the JSON safe-integer range." },
      { ru: "TOML date/time values сохраняются как strings с явным warning.", en: "TOML date/time values are preserved as strings with an explicit warning." },
    ],
    limitations: [
      { ru: "Это bounded configuration subset, а не полная parser implementation TOML 1.0.", en: "This is a bounded configuration subset, not a complete TOML 1.0 parser implementation." },
      { ru: "Multiline strings не поддерживаются; inf и nan отклоняются как непредставимые в JSON.", en: "Multiline strings are not supported; inf and nan are rejected because JSON cannot represent them." },
      { ru: "JSON null не имеет TOML 1.0 эквивалента и отклоняется при JSON → TOML.", en: "JSON null has no TOML 1.0 equivalent and is rejected during JSON → TOML conversion." },
    ],
    useCases: [
      { ru: "Преобразование application config для API или тестов.", en: "Converting application configuration for an API or tests." },
      { ru: "Проверка duplicate keys и type conflicts.", en: "Finding duplicate keys and type conflicts." },
      { ru: "Подготовка читаемого TOML из JSON-compatible object.", en: "Preparing readable TOML from a JSON-compatible object." },
    ],
    technicalNotes: [
      { ru: "Ввод ограничен 500 000 символов, 5 000 узлов и глубиной 32.", en: "Input is limited to 500,000 characters, 5,000 nodes, and depth 32." },
      { ru: "JSON → TOML принимает root object; arrays of objects выводятся как array tables.", en: "JSON → TOML accepts a root object; arrays of objects are emitted as array tables." },
    ],
    faq: [
      { question: { ru: "Почему даты становятся строками?", en: "Why do dates become strings?" }, answer: { ru: "JSON не имеет отдельного date/time типа. Инструмент сохраняет lexical TOML value как string и маркирует это warning.", en: "JSON has no dedicated date/time type. The tool preserves the lexical TOML value as a string and reports a warning." } },
      { question: { ru: "Поддерживается null?", en: "Is null supported?" }, answer: { ru: "Нет при JSON → TOML: TOML 1.0 не определяет null literal.", en: "Not for JSON → TOML: TOML 1.0 does not define a null literal." } },
    ],
    relatedToolSlugs: ["json-formatter-validator", "yaml-json-converter", "csv-json-converter"],
    sourceUrls: ["https://toml.io/en/v1.0.0"],
  }),
  toolPage({
    slug: "csv-json-converter",
    seoTitle: { ru: "CSV Data Workbench: проверка и CSV ↔ JSON", en: "CSV Data Workbench: Validation & CSV ↔ JSON" },
    metaDescription: { ru: "Проверяйте и преобразуйте CSV/JSON локально: delimiter detection, quoted и multiline fields, inconsistent rows, headers и formula-like signals.", en: "Validate and convert CSV/JSON locally with delimiter detection, quoted and multiline fields, inconsistent rows, headers, and formula-like signals." },
    h1: { ru: "CSV Data Workbench", en: "CSV Data Workbench" },
    lead: { ru: "Проверяйте структуру CSV и преобразуйте данные в JSON или обратно в одном bounded workflow вместо отдельного слабого validator.", en: "Validate CSV structure and convert data to JSON or back in one bounded workflow instead of a separate weak validator." },
    quickFacts: [
      { ru: "CSV ↔ JSON", en: "CSV ↔ JSON" },
      { ru: "Quoted multiline fields", en: "Quoted multiline fields" },
      { ru: "До 10 000 строк", en: "Up to 10,000 rows" },
    ],
    howToSteps: [
      { ru: "Выберите направление, delimiter и режим header.", en: "Choose direction, delimiter, and header mode." },
      { ru: "Вставьте CSV или JSON и запустите проверку.", en: "Paste CSV or JSON and run validation." },
      { ru: "Исправьте diagnostics или скопируйте результат conversion.", en: "Fix diagnostics or copy the converted output." },
    ],
    supportedFeatures: [
      { ru: "Comma, semicolon, tab и pipe delimiters с optional auto-detection.", en: "Comma, semicolon, tab, and pipe delimiters with optional auto-detection." },
      { ru: "Quoted fields, escaped double quotes, CRLF/LF и multiline quoted values.", en: "Quoted fields, escaped double quotes, CRLF/LF, and multiline quoted values." },
      { ru: "Inconsistent row, duplicate/empty header и formula-like field diagnostics.", en: "Inconsistent-row, duplicate/empty-header, and formula-like-field diagnostics." },
      { ru: "JSON arrays of objects или arrays; optional apostrophe prefix для formula-like CSV values.", en: "JSON arrays of objects or arrays; optional apostrophe prefix for formula-like CSV values." },
    ],
    limitations: [
      { ru: "Auto-detection является heuristic и должна проверяться на неоднозначных files.", en: "Auto-detection is heuristic and should be reviewed for ambiguous files." },
      { ru: "JSON → CSV принимает только scalar values и null; nested objects и arrays отклоняются.", en: "JSON → CSV accepts only scalar values and null; nested objects and arrays are rejected." },
      { ru: "Apostrophe prefix не является универсальной защитой для всех spreadsheet applications.", en: "An apostrophe prefix is not a universal protection for every spreadsheet application." },
    ],
    useCases: [
      { ru: "Проверка CSV export перед импортом.", en: "Checking a CSV export before import." },
      { ru: "Преобразование небольшого dataset в JSON fixtures.", en: "Converting a small dataset into JSON fixtures." },
      { ru: "Поиск inconsistent columns и опасных formula-like cells.", en: "Finding inconsistent columns and risky formula-like cells." },
    ],
    technicalNotes: [
      { ru: "Ввод ограничен 500 000 символов, 10 000 строк, 200 столбцов и 500 000 cells.", en: "Input is limited to 500,000 characters, 10,000 rows, 200 columns, and 500,000 cells." },
      { ru: "Проверка и преобразование CSV объединены в один публичный workflow, чтобы не дублировать функциональность отдельными инструментами.", en: "CSV validation and conversion are combined in one public workflow to avoid splitting duplicate functionality across separate tools." },
    ],
    faq: [
      { question: { ru: "Поддерживаются переносы строк внутри поля?", en: "Are line breaks inside a field supported?" }, answer: { ru: "Да, если поле заключено в двойные кавычки.", en: "Yes, when the field is enclosed in double quotes." } },
      { question: { ru: "Что означает formula-like field?", en: "What is a formula-like field?" }, answer: { ru: "Это значение, начинающееся с =, +, - или @ после optional whitespace. Инструмент маркирует такие значения и может префиксовать их апострофом при export.", en: "It is a value starting with =, +, -, or @ after optional whitespace. The tool flags these values and can prefix them with an apostrophe during export." } },
    ],
    relatedToolSlugs: ["json-formatter-validator", "jsonpath-tester", "toml-json-converter"],
    sourceUrls: ["https://www.rfc-editor.org/rfc/rfc4180.html", "https://owasp.org/www-community/attacks/CSV_Injection"],
  }),

  toolPage({
    slug: "json-schema-validator",
    seoTitle: { ru: "Проверка JSON по JSON Schema онлайн", en: "JSON Schema Validator Online" },
    metaDescription: { ru: "Проверьте JSON instance по документированному bounded subset JSON Schema 2020-12: типы, properties, required, arrays, combinators и локальные $ref.", en: "Validate a JSON instance against a documented bounded JSON Schema 2020-12 subset covering types, properties, required fields, arrays, combinators, and local $ref." },
    h1: { ru: "Проверка JSON по JSON Schema", en: "JSON Schema Validator" },
    lead: { ru: "Сопоставьте JSON-данные со schema и получите bounded список ошибок с instance path, keyword и объяснением.", en: "Check JSON data against a schema and receive a bounded list of issues with instance paths, keywords, and explanations." },
    quickFacts: [
      { ru: "Локально в браузере", en: "Runs locally" },
      { ru: "Local $ref", en: "Local $ref" },
      { ru: "До 10 000 узлов", en: "Up to 10,000 nodes" },
    ],
    howToSteps: [
      { ru: "Вставьте JSON instance.", en: "Paste the JSON instance." },
      { ru: "Вставьте JSON Schema.", en: "Paste the JSON Schema." },
      { ru: "Запустите проверку и изучите paths и keywords в отчёте.", en: "Run validation and review paths and keywords in the report." },
    ],
    supportedFeatures: [
      { ru: "type, enum, const, properties, required и additionalProperties.", en: "type, enum, const, properties, required, and additionalProperties." },
      { ru: "items, min/max items, uniqueItems и object/string/number constraints.", en: "items, min/max items, uniqueItems, and object/string/number constraints." },
      { ru: "allOf, anyOf, oneOf, not, $defs/definitions и локальные JSON Pointer $ref.", en: "allOf, anyOf, oneOf, not, $defs/definitions, and local JSON Pointer $ref." },
      { ru: "Ограниченная проверка форматов date, date-time, email, uri, uuid, IPv4, IPv6 и hostname.", en: "Bounded checks for date, date-time, email, uri, uuid, IPv4, IPv6, and hostname formats." },
    ],
    limitations: [
      { ru: "Это документированный subset, а не полная реализация JSON Schema 2020-12 meta-schema.", en: "This is a documented subset, not a complete JSON Schema 2020-12 meta-schema implementation." },
      { ru: "Remote $ref, dynamic references, unevaluated, conditional и content keywords не выполняются.", en: "Remote $ref, dynamic references, unevaluated, conditional, and content keywords are not executed." },
      { ru: "Проверка format является syntactic signal и не подтверждает существование email, URL или host.", en: "format checks are syntactic signals and do not confirm that an email, URL, or host exists." },
    ],
    useCases: [
      { ru: "Проверка API fixtures и конфигураций.", en: "Checking API fixtures and configurations." },
      { ru: "Диагностика required и additional properties.", en: "Diagnosing required and additional properties." },
      { ru: "Быстрая локальная проверка schema перед CI validator.", en: "Running a quick local check before a CI validator." },
    ],
    technicalNotes: [
      { ru: "Ввод ограничен 500 000 символов, 10 000 узлов и глубиной 64.", en: "Input is limited to 500,000 characters, 10,000 nodes, and depth 64." },
      { ru: "Отчёт ограничен 100 validation issues; достижение лимита маркируется как truncated.", en: "The report is limited to 100 validation issues and marks truncation when the limit is reached." },
    ],
    faq: [
      { question: { ru: "Поддерживается remote $ref?", en: "Are remote $ref values supported?" }, answer: { ru: "Нет. Инструмент разрешает только local JSON Pointer references внутри введённой schema и не выполняет сетевые запросы.", en: "No. The tool resolves only local JSON Pointer references inside the supplied schema and makes no network requests." } },
      { question: { ru: "Это замена Ajv или официального validator?", en: "Does this replace Ajv or a standards-complete validator?" }, answer: { ru: "Нет. Используйте специализированный standards-complete validator в CI, если проект зависит от полного vocabulary JSON Schema.", en: "No. Use a standards-complete validator in CI when your project depends on the full JSON Schema vocabulary." } },
    ],
    relatedToolSlugs: ["json-formatter-validator", "yaml-json-converter", "xml-formatter-validator"],
    sourceUrls: ["https://json-schema.org/draft/2020-12/json-schema-core.html", "https://json-schema.org/draft/2020-12/json-schema-validation.html"],
  }),
  toolPage({
    slug: "yaml-json-converter",
    seoTitle: { ru: "YAML в JSON и JSON в YAML онлайн", en: "YAML to JSON & JSON to YAML Converter" },
    metaDescription: { ru: "Преобразуйте JSON и безопасный configuration subset YAML локально в браузере. Anchors, aliases, custom tags, merge keys и block scalars отклоняются.", en: "Convert JSON and a safe YAML configuration subset locally in the browser. Anchors, aliases, custom tags, merge keys, and block scalars are rejected." },
    h1: { ru: "YAML ↔ JSON Converter", en: "YAML ↔ JSON Converter" },
    lead: { ru: "Преобразуйте mappings, sequences и scalars между JSON и предсказуемым YAML configuration subset без загрузки данных на сервер.", en: "Convert mappings, sequences, and scalars between JSON and a predictable YAML configuration subset without uploading data." },
    quickFacts: [
      { ru: "Два направления", en: "Two-way conversion" },
      { ru: "Safe subset", en: "Safe subset" },
      { ru: "До 5 000 узлов", en: "Up to 5,000 nodes" },
    ],
    howToSteps: [
      { ru: "Выберите YAML → JSON или JSON → YAML.", en: "Choose YAML → JSON or JSON → YAML." },
      { ru: "Вставьте документ и запустите преобразование.", en: "Paste the document and run the conversion." },
      { ru: "Скопируйте результат и проверьте его в целевом приложении.", en: "Copy the result and verify it in the target application." },
    ],
    supportedFeatures: [
      { ru: "Indented mappings и sequences с шагом два пробела.", en: "Indented mappings and sequences using two-space indentation." },
      { ru: "Plain, single-quoted и double-quoted scalars, numbers, booleans и null.", en: "Plain, single-quoted, and double-quoted scalars, numbers, booleans, and null." },
      { ru: "Inline arrays и objects при использовании JSON syntax.", en: "Inline arrays and objects when written with JSON syntax." },
      { ru: "JSON → YAML для JSON-compatible values с безопасным quoting неоднозначных строк.", en: "JSON → YAML for JSON-compatible values with safe quoting of ambiguous strings." },
    ],
    limitations: [
      { ru: "Это безопасный configuration subset, а не полная реализация YAML 1.2.2.", en: "This is a safe configuration subset, not a complete YAML 1.2.2 implementation." },
      { ru: "Anchors, aliases, custom tags, merge keys, complex keys и block scalars |/> отклоняются.", en: "Anchors, aliases, custom tags, merge keys, complex keys, and |/> block scalars are rejected." },
      { ru: "Комментарии не сохраняются при преобразовании в JSON и обратно.", en: "Comments are not preserved through JSON conversion and back." },
    ],
    useCases: [
      { ru: "Подготовка простой CI/CD или application config.", en: "Preparing a simple CI/CD or application configuration." },
      { ru: "Проверка duplicate keys и indentation ошибок.", en: "Finding duplicate keys and indentation errors." },
      { ru: "Преобразование безопасного fixture между JSON и YAML.", en: "Converting a safe fixture between JSON and YAML." },
    ],
    technicalNotes: [
      { ru: "YAML indentation должна использовать кратное двум количество пробелов; tabs запрещены.", en: "YAML indentation must use multiples of two spaces; tabs are rejected." },
      { ru: "Ввод ограничен 500 000 символов, 5 000 узлов и глубиной 32.", en: "Input is limited to 500,000 characters, 5,000 nodes, and depth 32." },
    ],
    faq: [
      { question: { ru: "Почему anchors и aliases запрещены?", en: "Why are anchors and aliases rejected?" }, answer: { ru: "Инструмент сознательно исключает graph-like и tag-driven features, чтобы conversion contract оставался bounded и предсказуемым.", en: "The tool deliberately excludes graph-like and tag-driven features so the conversion contract remains bounded and predictable." } },
      { question: { ru: "Сохраняются комментарии?", en: "Are comments preserved?" }, answer: { ru: "Нет. JSON не имеет модели комментариев, поэтому round trip не может сохранить их без отдельного AST contract.", en: "No. JSON has no comment model, so a round trip cannot preserve them without a separate AST contract." } },
    ],
    relatedToolSlugs: ["json-formatter-validator", "json-schema-validator", "xml-formatter-validator"],
    sourceUrls: ["https://yaml.org/spec/1.2.2/", "https://www.json.org/json-en.html"],
  }),
  toolPage({
    slug: "xml-formatter-validator",
    seoTitle: { ru: "XML Formatter и проверка well-formed XML", en: "XML Formatter & Well-Formedness Validator" },
    metaDescription: { ru: "Проверьте well-formed XML и отформатируйте структуру с отступом 2 или 4 пробела. DTD, ENTITY, XSD и external entity resolution отключены.", en: "Check well-formed XML and format its structure with two- or four-space indentation. DTD, ENTITY, XSD, and external entity resolution are disabled." },
    h1: { ru: "XML Formatter и Validator", en: "XML Formatter and Validator" },
    lead: { ru: "Проверьте matching tags, quoted attributes, entities и единственный root element, затем получите bounded форматированный документ.", en: "Check matching tags, quoted attributes, entities, and a single root element, then produce a bounded formatted document." },
    quickFacts: [
      { ru: "Well-formedness", en: "Well-formedness" },
      { ru: "DTD/ENTITY отключены", en: "DTD/ENTITY disabled" },
      { ru: "Mixed content сохраняется", en: "Mixed content preserved" },
    ],
    howToSteps: [
      { ru: "Вставьте XML и выберите размер отступа.", en: "Paste XML and choose the indentation size." },
      { ru: "Запустите проверку и форматирование.", en: "Run validation and formatting." },
      { ru: "Исправьте structural errors или скопируйте результат.", en: "Fix structural errors or copy the result." },
    ],
    supportedFeatures: [
      { ru: "Start/end/self-closing tags, quoted attributes и duplicate attribute detection.", en: "Start/end/self-closing tags, quoted attributes, and duplicate-attribute detection." },
      { ru: "XML comments, CDATA и processing instructions.", en: "XML comments, CDATA, and processing instructions." },
      { ru: "Predefined и numeric entity references без custom entity expansion.", en: "Predefined and numeric entity references without custom entity expansion." },
      { ru: "Форматирование structural content; mixed content остаётся compact.", en: "Formatting of structural content while mixed content remains compact." },
    ],
    limitations: [
      { ru: "XSD, Relax NG, Schematron и semantic namespace validation не выполняются.", en: "XSD, Relax NG, Schematron, and semantic namespace validation are not performed." },
      { ru: "DTD и ENTITY declarations отклоняются, external entities никогда не разрешаются.", en: "DTD and ENTITY declarations are rejected, and external entities are never resolved." },
      { ru: "Parser использует bounded conservative XML name subset и не является canonical XML serializer.", en: "The parser uses a bounded conservative XML-name subset and is not a canonical XML serializer." },
    ],
    useCases: [
      { ru: "Проверка API payload, feed или configuration XML.", en: "Checking an API payload, feed, or configuration XML." },
      { ru: "Поиск mismatched tags и duplicate attributes.", en: "Finding mismatched tags and duplicate attributes." },
      { ru: "Подготовка читаемой копии небольшого XML документа.", en: "Preparing a readable copy of a small XML document." },
    ],
    technicalNotes: [
      { ru: "Ввод ограничен 500 000 символов, 10 000 nodes и глубиной 64.", en: "Input is limited to 500,000 characters, 10,000 nodes, and depth 64." },
      { ru: "Formatter не вставляет indentation внутрь mixed content, чтобы не менять значащий текст.", en: "The formatter does not inject indentation inside mixed content so significant text is not changed." },
    ],
    faq: [
      { question: { ru: "Проверяется XML по XSD?", en: "Is XML validated against XSD?" }, answer: { ru: "Нет. Инструмент проверяет bounded well-formedness и formatting, но не schema conformance.", en: "No. The tool checks bounded well-formedness and formatting, not schema conformance." } },
      { question: { ru: "Безопасны ли external entities?", en: "Are external entities resolved?" }, answer: { ru: "Нет. DTD и ENTITY declarations отклоняются до parsing, поэтому XXE-style resolution не выполняется.", en: "No. DTD and ENTITY declarations are rejected before parsing, so XXE-style resolution is not performed." } },
    ],
    relatedToolSlugs: ["json-formatter-validator", "json-schema-validator", "yaml-json-converter"],
    sourceUrls: ["https://www.w3.org/TR/xml/"],
  }),
  toolPage({
    slug: "sql-formatter",
    seoTitle: { ru: "SQL Formatter онлайн без выполнения запроса", en: "SQL Formatter Online — Format Queries Locally" },
    metaDescription: { ru: "Отформатируйте SQL локально: clauses, joins, списки, вложенные subqueries, строки и комментарии. Запрос не отправляется на сервер и не выполняется.", en: "Format SQL locally with readable clauses, joins, lists, nested subqueries, strings, and comments. Queries are neither uploaded nor executed." },
    h1: { ru: "SQL Formatter для читаемых запросов", en: "SQL Formatter for Readable Queries" },
    lead: { ru: "Приведите SQL к последовательной структуре, сохранив quoted values и комментарии, без подключения к базе данных.", en: "Turn SQL into a consistent, reviewable layout while preserving quoted values and comments, with no database connection." },
    quickFacts: [
      { ru: "Локально в браузере", en: "Runs locally" },
      { ru: "Запрос не выполняется", en: "No query execution" },
      { ru: "Bounded tokenizer", en: "Bounded tokenizer" },
    ],
    howToSteps: [
      { ru: "Вставьте SQL и выберите регистр ключевых слов.", en: "Paste SQL and choose the keyword casing." },
      { ru: "Выберите отступ в 2 или 4 пробела и запустите форматирование.", en: "Choose two- or four-space indentation and run the formatter." },
      { ru: "Проверьте dialect warnings и скопируйте результат.", en: "Review any dialect warnings and copy the result." },
    ],
    supportedFeatures: [
      { ru: "Основные SELECT, INSERT, UPDATE, DELETE, WITH, UNION, JOIN и ordering/grouping clauses.", en: "Common SELECT, INSERT, UPDATE, DELETE, WITH, UNION, JOIN, ordering, and grouping clauses." },
      { ru: "Строки с escaped quotes, line/block comments и quoted identifiers.", en: "Strings with escaped quotes, line and block comments, and quoted identifiers." },
      { ru: "Вложенные subqueries с bounded depth и readable indentation.", en: "Nested subqueries with bounded depth and readable indentation." },
      { ru: "Upper, lower или preserved keyword casing.", en: "Uppercase, lowercase, or preserved keyword casing." },
    ],
    limitations: [
      { ru: "Это conservative formatter, а не полноценный parser PostgreSQL, MySQL, SQL Server, Oracle или SQLite.", en: "This is a conservative formatter, not a complete PostgreSQL, MySQL, SQL Server, Oracle, or SQLite parser." },
      { ru: "Semantic validation, schema resolution, query planning и выполнение SQL не выполняются.", en: "Semantic validation, schema resolution, query planning, and SQL execution are not performed." },
      { ru: "Редкие vendor-specific constructs могут быть сохранены, но не всегда получают идеальное форматирование.", en: "Uncommon vendor-specific constructs may be preserved without receiving ideal layout." },
    ],
    useCases: [
      { ru: "Подготовка запроса к code review.", en: "Preparing a query for code review." },
      { ru: "Чтение SQL из логов или миграций.", en: "Reading SQL copied from logs or migrations." },
      { ru: "Нормализация примера для документации или issue.", en: "Normalizing an example for documentation or an issue." },
    ],
    technicalNotes: [
      { ru: "Ввод ограничен 500 000 символов, 20 000 tokens и глубиной 64.", en: "Input is limited to 500,000 characters, 20,000 tokens, and depth 64." },
      { ru: "Formatter не подключается к СУБД и не передаёт SQL backend WebDiag.", en: "The formatter does not connect to a database or send SQL to the WebDiag backend." },
    ],
    faq: [
      { question: { ru: "Может ли инструмент проверить, что запрос выполнится?", en: "Can it confirm that the query will run?" }, answer: { ru: "Нет. Для этого нужен parser и schema конкретной СУБД либо безопасная тестовая база. Инструмент проверяет только bounded lexical structure и delimiters.", en: "No. That requires the target database parser and schema, or a controlled test database. This tool only checks bounded lexical structure and delimiters." } },
      { question: { ru: "SQL отправляется на сервер?", en: "Is the SQL uploaded?" }, answer: { ru: "Нет. Tokenization и форматирование выполняются локально в браузере.", en: "No. Tokenization and formatting run locally in your browser." } },
    ],
    relatedToolSlugs: ["json-formatter-validator", "graphql-formatter", "regex-tester"],
    sourceUrls: ["https://www.postgresql.org/docs/current/sql-syntax-lexical.html"],
  }),
  toolPage({
    slug: "graphql-formatter",
    seoTitle: { ru: "GraphQL Formatter для queries и fragments", en: "GraphQL Formatter for Queries and Fragments" },
    metaDescription: { ru: "Отформатируйте GraphQL queries, mutations, variables, directives и fragments локально. Проверяется lexical structure и баланс delimiters без schema validation.", en: "Format GraphQL queries, mutations, variables, directives, and fragments locally. Checks cover lexical structure and balanced delimiters, not schema validity." },
    h1: { ru: "GraphQL Formatter для документов и операций", en: "GraphQL Formatter for Documents and Operations" },
    lead: { ru: "Сделайте GraphQL-документ читаемым, сохранив comments, strings, block strings и fragment spreads.", en: "Make a GraphQL document easier to review while preserving comments, strings, block strings, and fragment spreads." },
    quickFacts: [
      { ru: "Queries и mutations", en: "Queries and mutations" },
      { ru: "Fragments и directives", en: "Fragments and directives" },
      { ru: "Без schema fetch", en: "No schema fetch" },
    ],
    howToSteps: [
      { ru: "Вставьте GraphQL document.", en: "Paste a GraphQL document." },
      { ru: "Выберите размер отступа и запустите formatter.", en: "Choose the indentation size and run the formatter." },
      { ru: "Проверьте структуру и скопируйте результат.", en: "Review the structure and copy the formatted document." },
    ],
    supportedFeatures: [
      { ru: "Operation definitions, variables, arguments и directives.", en: "Operation definitions, variables, arguments, and directives." },
      { ru: "Selection sets, aliases, fragments, inline fragments и type conditions.", en: "Selection sets, aliases, fragments, inline fragments, and type conditions." },
      { ru: "Comments, escaped strings и triple-quoted block strings.", en: "Comments, escaped strings, and triple-quoted block strings." },
      { ru: "Проверка matching braces, parentheses и brackets.", en: "Checks for matching braces, parentheses, and brackets." },
    ],
    limitations: [
      { ru: "Инструмент не загружает schema и не проверяет fields, arguments, variable types или deprecations.", en: "The tool does not load a schema or validate fields, arguments, variable types, or deprecations." },
      { ru: "Операция не отправляется GraphQL endpoint и не выполняется.", en: "The operation is not sent to a GraphQL endpoint or executed." },
      { ru: "Это bounded lexical formatter, а не полная реализация validation rules GraphQL specification.", en: "This is a bounded lexical formatter, not a complete implementation of GraphQL validation rules." },
    ],
    useCases: [
      { ru: "Подготовка query к pull request или документации.", en: "Preparing a query for a pull request or documentation." },
      { ru: "Разбор compact GraphQL payload из логов.", en: "Reviewing a compact GraphQL payload copied from logs." },
      { ru: "Проверка очевидно несбалансированных delimiters перед отладкой.", en: "Catching obviously unbalanced delimiters before debugging." },
    ],
    technicalNotes: [
      { ru: "Ввод ограничен 500 000 символов, 20 000 tokens и глубиной 64.", en: "Input is limited to 500,000 characters, 20,000 tokens, and depth 64." },
      { ru: "Commas считаются insignificant GraphQL tokens и не требуются в output.", en: "Commas are treated as insignificant GraphQL tokens and are not required in the output." },
    ],
    faq: [
      { question: { ru: "Проверяется ли query по моей schema?", en: "Is the query checked against my schema?" }, answer: { ru: "Нет. Schema introspection и remote endpoint access не входят в scope formatter.", en: "No. Schema introspection and remote endpoint access are outside the formatter's scope." } },
      { question: { ru: "Можно форматировать fragments и block strings?", en: "Can it format fragments and block strings?" }, answer: { ru: "Да, formatter сохраняет fragment spreads, comments, обычные и triple-quoted strings в рамках bounded lexical parser.", en: "Yes. The formatter preserves fragment spreads, comments, regular strings, and triple-quoted strings within its bounded lexical parser." } },
    ],
    relatedToolSlugs: ["json-formatter-validator", "sql-formatter", "regex-tester"],
    sourceUrls: ["https://spec.graphql.org/October2021/"],
  }),
  toolPage({
    slug: "regex-tester",
    seoTitle: { ru: "Safe Regex Lab с Web Worker timeout", en: "Safe Regex Lab with an Isolated Worker Timeout" },
    metaDescription: { ru: "Тестируйте JavaScript regex в отдельном Web Worker с hard timeout, match caps, captures и эвристическими ReDoS signals. Паттерн не выполняется на сервере.", en: "Test JavaScript regex in a dedicated Web Worker with a hard timeout, match caps, captures, and heuristic ReDoS signals. Patterns never run on the server." },
    h1: { ru: "Safe Regex Lab с изолированным выполнением", en: "Safe Regex Lab with Isolated Execution" },
    lead: { ru: "Проверьте JavaScript regular expression на bounded тексте, посмотрите captures и остановите слишком дорогой match принудительным timeout.", en: "Test a JavaScript regular expression against bounded input, inspect captures, and terminate expensive matching with a hard timeout." },
    quickFacts: [
      { ru: "Отдельный Web Worker", en: "Dedicated Web Worker" },
      { ru: "Hard timeout", en: "Hard timeout" },
      { ru: "До 500 matches", en: "Up to 500 matches" },
    ],
    howToSteps: [
      { ru: "Введите pattern без slash-разделителей и укажите JavaScript flags.", en: "Enter a pattern without slash delimiters and provide JavaScript flags." },
      { ru: "Вставьте тестовый текст и выберите timeout.", en: "Paste test input and choose a timeout." },
      { ru: "Запустите worker, затем проверьте matches, captures и risk signals.", en: "Run the worker, then review matches, captures, and risk signals." },
    ],
    supportedFeatures: [
      { ru: "JavaScript flags d, g, i, m, s, u, v и y с duplicate/conflict validation.", en: "JavaScript flags d, g, i, m, s, u, v, and y with duplicate and conflict validation." },
      { ru: "Match ranges, numbered captures, named captures и optional indices.", en: "Match ranges, numbered captures, named captures, and optional indices." },
      { ru: "Корректное продвижение zero-length global/sticky matches.", en: "Correct advancement for zero-length global or sticky matches." },
      { ru: "Heuristic review nested quantifiers, broad wildcards, quantified alternation, backreferences и large quantifiers.", en: "Heuristic review for nested quantifiers, broad wildcards, quantified alternation, backreferences, and large quantifiers." },
    ],
    limitations: [
      { ru: "Timeout ограничивает browser worker, но не доказывает, что pattern безопасен во всех runtimes и на всех данных.", en: "The timeout bounds the browser worker but does not prove that a pattern is safe in every runtime or against every input." },
      { ru: "Эвристические ReDoS signals могут давать false positives и false negatives.", en: "Heuristic ReDoS signals can produce both false positives and false negatives." },
      { ru: "Поддерживается JavaScript RegExp semantics, а не PCRE, RE2, .NET или Python regex dialect.", en: "The lab uses JavaScript RegExp semantics rather than PCRE, RE2, .NET, or Python regex dialects." },
    ],
    useCases: [
      { ru: "Проверка pattern и capture groups перед использованием во frontend.", en: "Checking a pattern and capture groups before frontend use." },
      { ru: "Сравнение flags и zero-length behavior.", en: "Comparing flags and zero-length behavior." },
      { ru: "Первичный review потенциально дорогого pattern до server-side benchmark.", en: "Performing an initial review of a potentially expensive pattern before server-side benchmarking." },
    ],
    technicalNotes: [
      { ru: "Pattern ограничен 2 000 символов, текст — 100 000 символов, output — 500 matches с bounded previews.", en: "Patterns are limited to 2,000 characters, input text to 100,000 characters, and output to 500 matches with bounded previews." },
      { ru: "Worker создаётся на один запуск, завершается после результата или timeout и не использует eval/Function.", en: "A fresh worker is created for each run, terminated after completion or timeout, and never uses eval or Function construction." },
    ],
    faq: [
      { question: { ru: "Гарантирует ли зелёный risk review отсутствие ReDoS?", en: "Does a low-risk review guarantee the pattern is ReDoS-free?" }, answer: { ru: "Нет. Нужны adversarial tests и benchmark в том runtime, где pattern будет работать в production.", en: "No. You still need adversarial tests and benchmarks in the exact runtime that will execute the pattern in production." } },
      { question: { ru: "Что происходит при зависании regex?", en: "What happens when matching stalls?" }, answer: { ru: "Main UI остаётся responsive, а отдельный Web Worker принудительно завершается после выбранного timeout.", en: "The main UI remains responsive, and the dedicated Web Worker is forcibly terminated after the selected timeout." } },
    ],
    relatedToolSlugs: ["sql-formatter", "graphql-formatter", "json-formatter-validator"],
    sourceUrls: ["https://developer.mozilla.org/docs/Web/JavaScript/Guide/Regular_expressions", "https://developer.mozilla.org/docs/Web/API/Web_Workers_API"],
  }),
  toolPage({
    slug: "cron-expression-workbench",
    seoTitle: { ru: "Cron Workbench: генератор, проверка и следующие запуски", en: "Cron Expression Workbench: Build, Validate & Preview" },
    metaDescription: { ru: "Соберите или проверьте 5-польное Unix cron-выражение, получите объяснение полей и bounded preview следующих запусков в UTC прямо в браузере.", en: "Build or validate a five-field Unix cron expression, inspect every field, and preview bounded next UTC occurrences directly in your browser." },
    h1: { ru: "Cron Expression Workbench для 5-польных расписаний", en: "Cron Expression Workbench for Five-Field Schedules" },
    lead: { ru: "Соберите расписание из пяти полей, проверьте lists, ranges и steps, разберите итоговое выражение и посмотрите до десяти следующих запусков в UTC.", en: "Build a five-field schedule, validate lists, ranges, and steps, inspect the normalized expression, and preview up to ten next UTC occurrences." },
    quickFacts: [
      { ru: "5-польный Unix cron", en: "Five-field Unix cron" },
      { ru: "Preview только в UTC", en: "UTC-only preview" },
      { ru: "Bounded Web Worker", en: "Bounded Web Worker" },
    ],
    howToSteps: [
      { ru: "Заполните отдельные поля или вставьте готовое cron-выражение.", en: "Fill the individual fields or paste an existing cron expression." },
      { ru: "Запустите проверку синтаксиса и диапазонов.", en: "Run syntax and range validation." },
      { ru: "Проверьте объяснение и следующие моменты запуска в UTC.", en: "Review the explanation and the next UTC occurrence timestamps." },
    ],
    supportedFeatures: [
      { ru: "Wildcards, числа, списки, диапазоны и steps.", en: "Wildcards, numeric values, lists, ranges, and steps." },
      { ru: "Названия месяцев JAN–DEC и дней недели SUN–SAT.", en: "JAN–DEC month names and SUN–SAT weekday names." },
      { ru: "Vixie-style OR semantics для одновременно ограниченных day-of-month и day-of-week.", en: "Vixie-style OR semantics when both day-of-month and day-of-week are restricted." },
      { ru: "До 10 будущих запусков с горизонтом 366 дней и жёстким timeout.", en: "Up to 10 future occurrences with a 366-day horizon and a hard timeout." },
    ],
    limitations: [
      { ru: "Seconds, year, Quartz tokens ?, L, W и #, macros и systemd timers не поддерживаются.", en: "Seconds, year, Quartz tokens ?, L, W, and #, macros, and systemd timers are not supported." },
      { ru: "Preview использует UTC и не моделирует IANA timezone или переходы DST.", en: "Preview uses UTC and does not model IANA timezones or DST transitions." },
      { ru: "Инструмент не создаёт и не выполняет реальные scheduler jobs.", en: "The tool does not create or execute real scheduler jobs." },
    ],
    useCases: [
      { ru: "Проверка расписания перед добавлением в crontab или CI job.", en: "Checking a schedule before adding it to crontab or a CI job." },
      { ru: "Поиск ошибки в диапазоне, списке или шаге.", en: "Finding an error in a range, list, or step." },
      { ru: "Проверка того, когда расписание сработает в UTC.", en: "Checking when a schedule will run in UTC." },
    ],
    technicalNotes: [
      { ru: "Выражение ограничено 256 символами, а preview — 10 результатами, 366 днями и фиксированным iteration cap.", en: "Expressions are limited to 256 characters, while preview is capped at 10 results, 366 days, and a fixed iteration limit." },
      { ru: "Расчёт следующих запусков выполняется в отдельном same-origin Web Worker, который завершается при timeout, reset или уходе со страницы.", en: "Next-occurrence calculation runs in a dedicated same-origin Web Worker that is terminated on timeout, reset, or component unmount." },
    ],
    faq: [
      { question: { ru: "Поддерживается ли шестое поле с секундами?", en: "Does it support a sixth seconds field?" }, answer: { ru: "Нет. Текущий contract ограничен стандартным пяти-польным Unix dialect: minute, hour, day-of-month, month и day-of-week.", en: "No. The current contract is limited to the five-field Unix dialect: minute, hour, day-of-month, month, and day-of-week." } },
      { question: { ru: "Почему результаты показаны только в UTC?", en: "Why are results shown only in UTC?" }, answer: { ru: "UTC делает preview детерминированным и не создаёт ложной совместимости с конкретным scheduler, timezone database или правилами DST.", en: "UTC keeps preview deterministic and avoids claiming compatibility with a particular scheduler, timezone database, or DST rule set." } },
    ],
    relatedToolSlugs: ["unix-timestamp-converter", "sql-formatter", "graphql-formatter"],
    sourceUrls: ["https://man7.org/linux/man-pages/man5/crontab.5.html"],
  }),
  toolPage({
    slug: "jwt-inspection-lab",
    seoTitle: { ru: "JWT Inspection Lab: header, payload и claims локально", en: "JWT Inspection Lab: Decode Header, Payload & Claims" },
    metaDescription: { ru: "Строго декодируйте compact JWT/JWS локально, изучите header, payload, exp, nbf, iat, iss и aud и получите security warnings без отправки токена на сервер.", en: "Strictly decode compact JWT/JWS locally, inspect header, payload, exp, nbf, iat, iss, and aud, and review security warnings without uploading the token." },
    h1: { ru: "JWT Inspection Lab для локальной проверки токена", en: "JWT Inspection Lab for Local Token Review" },
    lead: { ru: "Разберите три сегмента JWT/JWS, просмотрите JSON и зарегистрированные claims и отдельно оцените alg, подпись и временные значения без ложного заявления об аутентичности.", en: "Inspect the three JWT/JWS segments, review JSON and registered claims, and assess alg, signature presence, and timing values without claiming authenticity." },
    quickFacts: [
      { ru: "Только локальная обработка", en: "Local processing only" },
      { ru: "Строгий Base64URL и UTF-8", en: "Strict Base64URL and UTF-8" },
      { ru: "Decode не равен verify", en: "Decode is not verify" },
    ],
    howToSteps: [
      { ru: "Вставьте compact JWT/JWS из трёх сегментов.", en: "Paste a three-segment compact JWT/JWS." },
      { ru: "При необходимости выберите допустимый clock skew.", en: "Select an allowed clock skew when needed." },
      { ru: "Проверьте header, payload, temporal claims и security warnings.", en: "Review the header, payload, temporal claims, and security warnings." },
    ],
    supportedFeatures: [
      { ru: "Строгий разбор Base64URL, UTF-8 и JSON object для header и payload.", en: "Strict Base64URL, UTF-8, and JSON-object parsing for header and payload." },
      { ru: "Проверка exp, nbf и iat относительно часов браузера с настраиваемым clock skew.", en: "Inspection of exp, nbf, and iat against the browser clock with configurable clock skew." },
      { ru: "Review claims iss, sub, aud и jti и предупреждения для alg=none, missing alg и пустой signature.", en: "Review of iss, sub, aud, and jti claims plus warnings for alg=none, missing alg, and an empty signature." },
    ],
    limitations: [
      { ru: "Подпись не проверяется, authenticity и допустимость токена не подтверждаются.", en: "The signature is not verified, and token authenticity or acceptability is not confirmed." },
      { ru: "JWE, remote JWKS, OAuth/OIDC discovery, token exchange и private keys не поддерживаются.", en: "JWE, remote JWKS, OAuth/OIDC discovery, token exchange, and private keys are not supported." },
      { ru: "Временные статусы зависят от часов браузера и не заменяют проверку на принимающем сервере.", en: "Timing statuses depend on the browser clock and do not replace validation by the accepting server." },
    ],
    useCases: [
      { ru: "Просмотр claims тестового access или ID token во время разработки.", en: "Reviewing claims in a test access or ID token during development." },
      { ru: "Поиск malformed Base64URL, JSON или NumericDate.", en: "Finding malformed Base64URL, JSON, or NumericDate values." },
      { ru: "Проверка того, почему exp или nbf выглядит некорректно.", en: "Investigating why exp or nbf appears incorrect." },
    ],
    technicalNotes: [
      { ru: "JWT ограничен 64 KiB, JSON — глубиной 64 и 5 000 nodes; токен не сохраняется, не логируется и не отправляется по сети.", en: "JWT input is capped at 64 KiB and JSON at depth 64 and 5,000 nodes; the token is not stored, logged, or sent over the network." },
      { ru: "Декодированные значения выводятся как text/JSON и не вставляются в HTML через динамическую разметку.", en: "Decoded values are rendered as text/JSON and are not inserted through dynamic HTML markup." },
    ],
    faq: [
      { question: { ru: "Декодирование подтверждает подпись JWT?", en: "Does decoding verify a JWT signature?" }, answer: { ru: "Нет. Любой может сформировать похожие header и payload. Подлинность требует проверки signature с доверенным ключом, алгоритмом и policy на стороне принимающей системы.", en: "No. Anyone can construct similar header and payload data. Authenticity requires signature verification with a trusted key, algorithm, and policy in the accepting system." } },
      { question: { ru: "Инструмент загружает токен или получает JWKS?", en: "Does the tool upload the token or fetch JWKS?" }, answer: { ru: "Нет. Обработка выполняется локально, сетевые запросы, история и persistent storage не используются.", en: "No. Processing is local, and the tool uses no network requests, history, or persistent storage." } },
    ],
    relatedToolSlugs: ["base64-converter", "json-formatter-validator", "unix-timestamp-converter"],
    sourceUrls: ["https://www.rfc-editor.org/rfc/rfc7519", "https://www.rfc-editor.org/rfc/rfc7515"],
  }),
] as const;
